version: "3.8"
services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - docker_network
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_data:/var/www/html/wordpress"
    restart: always
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - "mariadb_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - docker_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}

networks:
  docker_network:
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/tnave/Desktop/wordpress
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/tnave/Desktop/mariadb
      o: bind
