version: "3.8"
services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - docker_network
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_data:/var/www/html/wordpress"
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_TITLE: ${WP_TITLE}
      WP_EMAIL: ${WP_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - "mariadb_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - docker_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}

networks:
  docker_network:
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tnave/data/wordpress
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tnave/data/mariadb
      o: bind
