version: "3.8"
services:
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:inception
    networks:
      - docker_network
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:inception
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  # mariadb:

networks:
  docker_network:
# MYSQL_PASSWORD: ${MYSQL_PASSWORD}
# Same for others value into .env

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/tnave/Desktop/wordpress
      o: bind
