USE mysql;
-- FLUSH PRIVILEGES;
-- DELETE FROM	mysql.user WHERE User='';
-- DROP DATABASE test;
-- DELETE FROM mysql.db WHERE Db='test';
-- DELETE FROM mysql.user WHERE User='theodorenave' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
CREATE DATABASE wordpress CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'root'@'%' IDENTIFIED by 'root';
GRANT ALL PRIVILEGES ON wordpress.* TO 'root'@'%';
-- grant ALL PRIVILEGES on *.* to tnave@wordpress.srcs_docker_network identified by 'tnave' with grant option;
FLUSH PRIVILEGES;