USE mysql;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
CREATE DATABASE $WP_DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER '$WP_ROOT_USR'@'%' IDENTIFIED by '$WP_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON $WP_DATABASE.* TO '$WP_ROOT_USR'@'%';
FLUSH PRIVILEGES;